### ISSUE TITLE
适用版本疑问

### ISSUE THREAD

**Issue by qinghao101** [ScmTble/NH50_70RA-Z7M-CT7NA-Hackintosh#1]
首先，先感谢您无私的分享，这个efi使小白的我有更多的尝试，不过我有个疑问，请问一下，这个测试的时候使用的哪个版本的系统？如10.15.4,12.6等，希望可以得到回复，感谢🙏

**Comment by scmtble** [comment]
这个efi的网卡驱动版本适合12.6，如果想安装macos11需要自己更换驱动
